// Code generated by Slice Machine. DO NOT EDIT.

import Logos from './Logos/index.svelte';
import Opener from './Opener/index.svelte';
import RichText from './RichText/index.svelte';
import Shop from './Shop/index.svelte';

export const components = {
	logos: Logos,
	opener: Opener,
	rich_text: RichText,
	shop: Shop
};
